### ISSUE TITLE
Unable to fetch my PLAYLISTS

### ISSUE THREAD

**Issue by RaiPeter** [CleverProgrammers/spotify-clone#23]
I'm pretty much sure I have written the code correctly but still I'm failing to fetch my playlists from Spotify pls help

**Comment by KamalEzzikouri** [comment]
the problem is the missing of some scopes:
I fixed the problem for the project and i asked for a Pull request.
in your [spotify].js change the scopes to this:
```
//  Visit me at: kamalezzikouri.com
const scopes = [
  "user-read-playback-position",
  "user-read-email",
  "user-library-modify",
  "playlist-modify-public",
  "ugc-image-upload",
  "user-follow-modify",
  "user-modify-playback-state",
  "user-read-recently-played",
  "user-read-private",
  "user-library-read",
  "user-top-read",
  "playlist-modify-private",
  "user-follow-read",
  "user-read-playback-state",
  "user-read-currently-playing",
  "playlist-read-private",
  "playlist-read-collaborative",
];
```

**Comment by biancadevelop** [comment]
I am also having this issue right now, I added those additional scopes but still cant display the playlist

**Comment by isahilsachdev** [comment]
Thank you bro , it worked

**Comment by KamalEzzikouri** [comment]
> I am also having this issue right now, I added those additional scopes but still cant display the playlist

please you can contact me [here](http://www.kamalezzikouri.com/)

**Comment by parul395** [comment]
can anyone help me with same issue, I added the above scopes, it didn't work.

**Comment by parul395** [comment]
hello Kamal,"Your requested URL has been blocked as per the directions received from Department of Telecommunications, Government of India. Please contact administrator for more information." I get this when i try to contact you, please help.

**Comment by KamalEzzikouri** [comment]
> hello Kamal,"Your requested URL has been blocked as per the directions received from Department of Telecommunications, Government of India. Please contact administrator for more information." I get this when i try to contact you, please help.

Hey, You can contact me here => [Link](https://www.linkedin.com/in/kamalezzikouri/) or you can use telegram => @[kamalezzikouri](https://t.me/kamalezzikouri/)

**Comment by tambi-ayush** [comment]
> the problem is the missing of some scopes: I fixed the problem for the project and i asked for a Pull request. in your [spotify].js change the scopes to this:
> 
> ```
> //  Visit me at: kamalezzikouri.com
> const scopes = [
>   "user-read-playback-position",
>   "user-read-email",
>   "user-library-modify",
>   "playlist-modify-public",
>   "ugc-image-upload",
>   "user-follow-modify",
>   "user-modify-playback-state",
>   "user-read-recently-played",
>   "user-read-private",
>   "user-library-read",
>   "user-top-read",
>   "playlist-modify-private",
>   "user-follow-read",
>   "user-read-playback-state",
>   "user-read-currently-playing",
>   "playlist-read-private",
>   "playlist-read-collaborative",
> ];
> ```

thanks this works even me thanks a lot

**Comment by neostiv** [comment]
Yes, gret job it worked. anks.
